name: Node.js CI

on:
    workflow_dispatch:

env:
    CI: true
    FORCE_COLOR: 2
    NODE_COV: lts/* # The Node.js version to run coveralls on

permissions:
    contents: read #  to fetch code (actions/checkout)

jobs:
    lint:
        runs-on: ubuntu-22.04-ppc64le
        steps:
            - uses: actions/checkout@v4.2.1
              with:
                  submodules: recursive
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  architecture: ppc64le
                  cache: npm
            - run: npm ci
            - run: npm run lint

    test:
        permissions:
            contents: read #  to fetch code (actions/checkout)
            checks: write #  to create new checks (coverallsapp/github-action)

        name: Node ${{ matrix.node }}
        runs-on: ubuntu-22.04-ppc64le

        strategy:
            fail-fast: false
            matrix:
                node:
                    - 18
                    - 20

        steps:
            - uses: actions/checkout@v4.2.1
              with:
                  submodules: recursive
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
                  architecture: ppc64le
                  cache: npm
            - run: npm ci
            - run: npm run build --if-present

            - name: Run Jest
              run: npm run unit-tests
              if: matrix.node != env.NODE_COV

            - name: Run Jest with coverage
              run: npm run unit-tests -- --coverage
              if: matrix.node == env.NODE_COV

            - name: Run Coveralls
              uses: coverallsapp/github-action@v2.3.1
              if: matrix.node == env.NODE_COV
              continue-on-error: true
              with:
                  github-token: '${{ secrets.GITHUB_TOKEN }}'
